# Generated by Django 5.1.4 on 2024-12-30 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0003_personcv_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personcv',
            name='user',
        ),
    ]
